### Rubocop Template For Productive Teams (v0.9.0)
### https://github.com/westonganger/rubocop_template_for_productive_teams

### Rubocop v1.1.0
### Warning: Be very vigilant when upgrading Rubocop, very consistently there are new cops that will negatively affect your workflow 
### Docs: https://docs.rubocop.org/rubocop/1.1/index.html
### Code: https://github.com/rubocop-hq/rubocop/tree/v1.1.0/lib/rubocop/cop

require:
  - ./rubocop/load_all_custom_cops.rb
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rspec

inherit_from:
  - .rubocop_minitest.yml
  - .rubocop_rspec.yml

AllCops:
  EnabledByDefault: true
  NewCops: enable
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.prawn"
    - "**/*.axlsx"
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '**/*.slim'
    - '**/*.haml'
    - '**/*.erb'

Minitest:
  Include:
    - 'test/**/*_test.rb'


##########################################################
# Bundler
##########################################################

Bundler/GemComment:
  Enabled: false


##########################################################
# Custom Cops - defined in ./rubocop/custom_cops/
##########################################################

Custom/InstanceVariableInClassMethod: 
  Enabled: true

Custom/NamedValidations:
  Enabled: true

Custom/ValidationNaming:
  Enabled: true


##########################################################
# Layout
##########################################################

Layout/ArgumentAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLineAfterMultilineCondition:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineArrayLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false


##########################################################
# Lint
##########################################################

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/EmptyEnsure:
  Enabled: false

Lint/HeredocMethodCallPosition:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false


##########################################################
# Metrics
##########################################################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


##########################################################
# Naming
##########################################################

Naming/AccessorMethodName:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

  
##########################################################
# Performance - rubocop-performance
##########################################################

Performance/ChainArrayAllocation:
  Enabled: false


##########################################################
# Rails - rubocop-rails
##########################################################

Rails/ActiveSupportAliases:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/AssertNot:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/ContentTag:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/IndexBy:
  Enabled: false

Rails/IndexWith:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/Pick:
  Enabled: false

Rails/PluckId:
  Enabled: false

Rails/PluralizationGrammar:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Rails/RequestReferer:
  Enabled: false

Rails/SafeNavigation:
  Enabled: false

Rails/ShortI18n:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

##########################################################
# Security
##########################################################

Security/YAMLLoad:
  Enabled: false

##########################################################
# Style
##########################################################

Style/AccessorGrouping:
  Enabled: false
  
Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLambdaParameter:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/Next:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/OrAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ReturnNil:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Send:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false 
