##########################################################
# Minitest - rubocop-minitest
##########################################################

Minitest/AssertEmpty:
  Enabled: false

Minitest/AssertEmptyLiteral:
  Enabled: false

Minitest/AssertEqual:
  Enabled: false

Minitest/AssertInDelta:
  Enabled: false

Minitest/AssertionInLifecycleHook:
  Enabled: false

Minitest/AssertMatch:
  Enabled: false

Minitest/AssertIncludes:
  Enabled: false

Minitest/AssertInstanceOf:
  Enabled: false

Minitest/AssertKindOf:
  Enabled: false

Minitest/AssertNil:
  Enabled: false

Minitest/AssertOutput:
  Enabled: false

Minitest/AssertPathExists:
  Enabled: false

Minitest/AssertRespondTo:
  Enabled: false

Minitest/AssertSilent:
  Enabled: false

Minitest/AssertTruthy:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Minitest/RefuteEmpty:
  Enabled: false

Minitest/RefuteEqual:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/RefuteInDelta:
  Enabled: false

Minitest/RefuteIncludes:
  Enabled: false

Minitest/RefuteMatch:
  Enabled: false

Minitest/RefuteInstanceOf:
  Enabled: false

Minitest/RefuteKindOf:
  Enabled: false

Minitest/RefuteNil:
  Enabled: false

Minitest/RefutePathExists:
  Enabled: false

Minitest/RefuteRespondTo:
  Enabled: false
